[package]
name = "phoxal-runtime-localize"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "phoxal_runtime_localize"
path = "src/lib.rs"

[dependencies]
phoxal = { workspace = true, features = ["scenario"] }
async-trait = { workspace = true }
phoxal-runtime-localize-orb-slam3-sys = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
