//! Lower mismatched latest observations into one robot-owned runtime target.
//!
//! This stage runs after exact participant preparation and before Cargo reads
//! the root package targets. The author's `robot.yaml` remains the source of
//! connection intent; the returned document is the executable graph.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::Command;

use phoxal::artifact::document::{
    ConnectionSources, PortReference, RobotDocument, ServiceSelection, Source,
};
use phoxal::artifact::{InputRole, MethodShape, RuntimeRecord};

use super::{CargoOperation, CargoOptions, Error, ProjectLayout, cargo, manifest_check, selection};

pub(super) const INSTANCE: &str = "phoxal-adapter";
const BINARY: &str = "phoxal-adapter";
const MARKER: &str = "// @generated by cargo-phoxal; do not edit.\n";

struct Edge {
    consumer: String,
    producer: String,
    source_type: String,
    destination_type: String,
    max_age_ms: Option<u64>,
    input_max_bytes: u64,
    output_max_bytes: u64,
    period_ms: u64,
    timeout_ms: u64,
    init_timeout_ms: u64,
}

/// Generate the adapter target, when an exact selected output does not match
/// its latest-value consumer, and return the graph that executes it.
pub(crate) fn lower(
    layout: &ProjectLayout,
    authored: &RobotDocument,
    options: &CargoOptions,
) -> Result<RobotDocument, Error> {
    let RobotDocument::V0 {
        robot,
        services,
        connections,
        ..
    } = authored;
    let mut contracts = BTreeMap::new();
    for (instance, selection) in services {
        if let Some(contract) = read_contract(
            layout.root(),
            &selection.source,
            selection.binary.as_deref(),
        )? {
            contracts.insert(instance.as_str(), contract);
        }
    }
    for (instance, component) in &robot.components {
        if component.driver.is_some()
            && let Some(contract) = read_contract(
                layout.root(),
                &component.source,
                component.binary.as_deref(),
            )?
        {
            contracts.insert(instance.as_str(), contract);
        }
    }
    if connections.iter().any(|(consumer, sources)| {
        PortReference::parse(consumer).is_ok_and(|port| port.instance == "brain")
            || matches!(sources, ConnectionSources::One(source)
                if PortReference::parse(source).is_ok_and(|port| port.instance == "brain"))
    }) {
        contracts.insert("brain", read_brain_contract(layout, authored, options)?);
    }

    let mut edges = Vec::new();
    for (consumer_text, sources) in connections {
        let ConnectionSources::One(producer_text) = sources else {
            continue;
        };
        let Ok(consumer) = PortReference::parse(consumer_text) else {
            continue;
        };
        let Ok(producer) = PortReference::parse(producer_text) else {
            continue;
        };
        let (Some(consumer_contract), Some(producer_contract)) = (
            contracts.get(consumer.instance.as_str()),
            contracts.get(producer.instance.as_str()),
        ) else {
            continue;
        };
        let RuntimeRecord::V0 {
            inputs,
            period_ms,
            timeout_ms,
            init_timeout_ms,
            ..
        } = consumer_contract;
        let Some(input) = inputs.iter().find(|input| input.name == consumer.port) else {
            continue;
        };
        let RuntimeRecord::V0 {
            service_outputs,
            transient_outputs,
            ..
        } = producer_contract;
        let Some(output) = service_outputs
            .iter()
            .chain(transient_outputs)
            .find(|output| {
                output
                    .signature
                    .as_ref()
                    .is_some_and(|signature| signature.endpoint == producer.port)
            })
        else {
            continue;
        };
        let Some(signature) = output.signature.as_ref() else {
            continue;
        };
        if input.role != InputRole::ObservationLatest || signature.shape != MethodShape::Observation
        {
            // Calls and leased commands compare their request payloads in
            // ordinary compiled connection validation, not this adapter.
            continue;
        }
        let Some(destination_type) = input.response_fqn.as_deref() else {
            continue;
        };
        if destination_type == signature.response {
            continue;
        }
        if !signature.retained_latest
            || signature.request != "google.protobuf.Empty"
            || signature.lease_valid_for_ms.is_some()
        {
            return Err(Error::DeclarationCheck {
                message: format!(
                    "{consumer_text} <- {producer_text}: different payloads require a latest-observation conversion; this delivery shape has no robot adapter yet"
                ),
            });
        }
        edges.push(Edge {
            consumer: consumer_text.clone(),
            producer: producer_text.clone(),
            source_type: signature.response.clone(),
            destination_type: destination_type.to_owned(),
            max_age_ms: input.max_age_ms,
            input_max_bytes: output.max_bytes.ok_or_else(|| Error::DeclarationCheck {
                message: format!(
                    "{producer_text}: a converted observation needs a compiled output byte bound"
                ),
            })?,
            output_max_bytes: input.max_bytes.ok_or_else(|| Error::DeclarationCheck {
                message: format!(
                    "{consumer_text}: a converted observation needs a compiled input byte bound"
                ),
            })?,
            period_ms: *period_ms,
            timeout_ms: *timeout_ms,
            init_timeout_ms: *init_timeout_ms,
        });
    }

    let source_path = layout.root().join("src/bin").join(format!("{BINARY}.rs"));
    if edges.is_empty() {
        remove_generated(&source_path)?;
        return Ok(authored.clone());
    }
    if services.contains_key(INSTANCE) || robot.components.contains_key(INSTANCE) {
        return Err(Error::DeclarationCheck {
            message: format!("{INSTANCE} is reserved for the generated robot conversion target"),
        });
    }
    write_generated(&source_path, &generate(&edges))?;
    let mut executable = authored.clone();
    let RobotDocument::V0 {
        services,
        connections,
        ..
    } = &mut executable;
    services.insert(
        INSTANCE.to_owned(),
        ServiceSelection {
            source: Source::Path(".".to_owned()),
            binary: Some(BINARY.to_owned()),
            config: None,
        },
    );
    for (index, edge) in edges.iter().enumerate() {
        connections.insert(
            format!("{INSTANCE}.source_{index}"),
            ConnectionSources::One(edge.producer.clone()),
        );
        connections.insert(
            edge.consumer.clone(),
            ConnectionSources::One(format!("{INSTANCE}.target_{index}")),
        );
    }
    Ok(executable)
}

fn read_brain_contract(
    layout: &ProjectLayout,
    authored: &RobotDocument,
    options: &CargoOptions,
) -> Result<RuntimeRecord, Error> {
    let metadata = cargo::load_metadata_at(layout.cargo_manifest(), layout.root(), None, options)?;
    let root = metadata
        .root_package()
        .ok_or(super::error::SourceError::MissingBrain)?;
    let RobotDocument::V0 { brain, .. } = authored;
    let generated_path = layout.root().join("src/bin").join(format!("{BINARY}.rs"));
    let generated_adapter =
        fs::read_to_string(&generated_path).is_ok_and(|source| source.starts_with(MARKER));
    let target = selection::resolve_brain(root, brain.as_ref(), &metadata, generated_adapter)?;
    let mut command = Command::new(options.cargo_program());
    command
        .current_dir(layout.root())
        .args(["build", "--manifest-path"]);
    command.arg(layout.cargo_manifest());
    if let Some(config) = cargo::registry_config(layout.root()) {
        command.args(["--config", &config]);
    }
    let mut build_options = options.clone();
    build_options.cargo_args.clear();
    build_options.test_args.clear();
    build_options.append_common(&mut command, false, false);
    command.args(["--package", &target.package, "--bin", &target.target]);
    command.args(["--message-format", "json-render-diagnostics"]);
    let output = cargo::run_command(command, CargoOperation::Build)?;
    let executable = cargo::artifact_path(&output.stdout, &target)?;
    let contract = super::artifact::inspect_file(&executable).map_err(|error| match error {
        super::artifact::Error::MissingRecord => Error::MissingArtifactContract {
            role: "brain".to_owned(),
            instance: "brain".to_owned(),
            package: target.package.clone(),
            target: target.target.clone(),
        },
        other => Error::ArtifactInvalid {
            path: executable.clone(),
            message: other.to_string(),
        },
    })?;
    let descriptors = super::participant::merge_descriptor_closures(&contract)?;
    let prepared_dir = phoxal_build::self_prepared_dir(layout.root());
    let selection = phoxal_build::PreparedSelection::SelfHosted {
        package: target.package.clone(),
    };
    let executable_record = phoxal_build::PreparedExecutable {
        sha256: super::participant::digest_of(&executable)?,
        package: target.package.clone(),
        version: Some(root.version.to_string()),
    };
    if !phoxal_build::read_prepared(&prepared_dir)
        .is_ok_and(|prepared| prepared.file.executable == executable_record)
    {
        super::participant::write_prepared_contract(
            &prepared_dir,
            &selection,
            None,
            &contract.runtime,
            &descriptors,
            &executable_record,
        )?;
    }
    Ok(contract.runtime)
}

fn read_contract(
    root: &Path,
    source: &Source,
    binary: Option<&str>,
) -> Result<Option<RuntimeRecord>, Error> {
    let contract_dir = manifest_check::prepared_root(root, source, binary);
    if !contract_dir.join(phoxal_build::CONTRACT_FILE).is_file() {
        return Ok(None);
    }
    let prepared = phoxal_build::read_prepared_for(
        &contract_dir,
        &manifest_check::selection_identity(source),
        binary,
    )
    .map_err(|error| Error::DeclarationCheck {
        message: format!("{error}"),
    })?;
    let record =
        serde_json::from_value(prepared.file.runtime).map_err(|error| Error::DeclarationCheck {
            message: format!(
                "invalid prepared runtime {}: {error}",
                contract_dir.display()
            ),
        })?;
    Ok(Some(record))
}

fn write_generated(path: &Path, contents: &str) -> Result<(), Error> {
    if let Ok(existing) = fs::read_to_string(path) {
        if !existing.starts_with(MARKER) {
            return Err(Error::DeclarationCheck {
                message: format!("{} is not a cargo-phoxal generated file", path.display()),
            });
        }
        if existing == contents {
            return Ok(());
        }
    }
    let parent = path.parent().ok_or_else(|| Error::DeclarationCheck {
        message: format!("generated path {} has no parent", path.display()),
    })?;
    fs::create_dir_all(parent).map_err(|source| Error::ArtifactFile {
        path: parent.to_owned(),
        source,
    })?;
    fs::write(path, contents).map_err(|source| Error::ArtifactFile {
        path: path.to_owned(),
        source,
    })
}

fn remove_generated(path: &Path) -> Result<(), Error> {
    if fs::read_to_string(path).is_ok_and(|source| source.starts_with(MARKER)) {
        fs::remove_file(path).map_err(|source| Error::ArtifactFile {
            path: path.to_owned(),
            source,
        })?;
    }
    Ok(())
}

fn type_path(identity: &str) -> String {
    phoxal_build::sdk_type_path(identity)
        .unwrap_or_else(|| format!("crate::api::types::{}", identity.replace('.', "::")))
}

fn generate(edges: &[Edge]) -> String {
    // Every edge is a selected compiled consumer; its runtime timing is the
    // adapter's scheduling source. A faster consumer cadence takes priority.
    let period_ms = edges.iter().map(|edge| edge.period_ms).min().unwrap_or(1);
    let timeout_ms = edges.iter().map(|edge| edge.timeout_ms).max().unwrap_or(1);
    let init_timeout_ms = edges
        .iter()
        .map(|edge| edge.init_timeout_ms)
        .max()
        .unwrap_or(1);
    let mut source = String::from(MARKER);
    source.push_str("#![allow(\n    clippy::too_many_lines,\n    clippy::unnecessary_fallible_conversions,\n    reason = \"generated adapter supports both From and TryFrom conversions\"\n)]\n\n");
    source.push_str("#[path = \"../conversions.rs\"]\nmod conversions;\n\nphoxal::api!();\n\n");
    // The brain-side payloads' generated bindings carry no linker-retained
    // schema frames (the brain authors those definitions itself), so this
    // adapter — and only this adapter — includes the build helper's
    // retained-frame file for them: its compiled artifact must define the
    // complete reachable schema of every payload it serves, nested
    // messages, enumerations, and payload-enum variants included.
    source.push_str("include!(concat!(env!(\"OUT_DIR\"), \"/phoxal-self-retention.rs\"));\n\n");
    source.push_str("use phoxal::runtime::input::Latest;\n");
    source.push_str("use phoxal::runtime::{InitContext, Runtime, Sample, StepContext};\n\n");
    for (index, edge) in edges.iter().enumerate() {
        let destination = type_path(&edge.destination_type);
        let _ = writeln!(
            source,
            "const TARGET_{index}: phoxal::contracts::ObservationMethod<\n    {destination},\n> = phoxal::contracts::ObservationMethod::new(\n    \"{}\",\n    \"target_{index}\",\n    \"target_{index}\",\n    \"google.protobuf.Empty\",\n    \"{}\",\n    true,\n    None,\n    &[],\n);",
            edge.destination_type, edge.destination_type
        );
    }
    source.push_str("\n#[phoxal::runtime::inputs]\n#[derive(Default)]\nstruct Inputs {\n");
    for (index, edge) in edges.iter().enumerate() {
        let _ = writeln!(source, "    // {} <- {}", edge.consumer, edge.producer);
        if let Some(max_age_ms) = edge.max_age_ms {
            let _ = writeln!(
                source,
                "    #[phoxal::runtime::input(max_age_ms = {max_age_ms}, max_bytes = {})]",
                edge.input_max_bytes
            );
        } else {
            let _ = writeln!(
                source,
                "    #[phoxal::runtime::input(max_bytes = {})]",
                edge.input_max_bytes
            );
        }
        let _ = writeln!(
            source,
            "    source_{index}: Latest<{}>,",
            type_path(&edge.source_type)
        );
    }
    source.push_str("}\n\n#[phoxal::runtime::outputs]\n#[derive(Default)]\nstruct Outputs {\n");
    for (index, edge) in edges.iter().enumerate() {
        let _ = writeln!(
            source,
            "    #[phoxal::runtime::outputs::state(port = TARGET_{index}.state_port(), max_bytes = {})]",
            edge.output_max_bytes
        );
        let _ = writeln!(
            source,
            "    target_{index}: Option<Sample<{}>>,",
            type_path(&edge.destination_type)
        );
    }
    source.push_str("}\n\nstruct Adapter;\n\n");
    let _ = writeln!(
        source,
        "#[phoxal::runtime(period_ms = {period_ms}, timeout_ms = {timeout_ms}, init_timeout_ms = {init_timeout_ms})]"
    );
    source.push_str("impl Runtime for Adapter {\n    type Config = ();\n    type State = ();\n    type Inputs = Inputs;\n    type Outputs = Outputs;\n\n    fn init(&self, _ctx: &InitContext, _config: ()) -> phoxal::Result<()> {\n        Ok(())\n    }\n\n    fn step(&self, ctx: &StepContext, state: (), inputs: &Inputs) -> phoxal::Result<((), Outputs)> {\n        let mut outputs = Outputs::default();\n");
    for (index, edge) in edges.iter().enumerate() {
        let destination = type_path(&edge.destination_type);
        let producer = &edge.producer;
        let consumer = &edge.consumer;
        let _ = writeln!(
            source,
            "        if inputs.source_{index}.is_fresh_at(ctx.now(), {:?})",
            edge.max_age_ms
        );
        let _ = writeln!(
            source,
            "            && let Some(sample) = inputs.source_{index}.sample()"
        );
        source.push_str("        {\n");
        let _ = writeln!(
            source,
            "            let converted: {destination} = sample.payload().clone().try_into().map_err(|error| phoxal::macro_support::anyhow::anyhow!(\"{consumer} <- {producer}: {{error:?}}\"))?;"
        );
        let _ = writeln!(
            source,
            "            outputs.target_{index} = Some(Sample::new(converted, sample.stamp().clone()));"
        );
        source.push_str("        }\n");
    }
    source.push_str("        Ok((state, outputs))\n    }\n}\n\n#[phoxal::runtime::outputs]\nimpl Adapter {}\n\nfn main() -> phoxal::Result<()> {\n    phoxal::runtime::run(Adapter)\n}\n");
    source
}
