//! Preparation of the project-local generated `robot_api` crate.

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use heck::{ToShoutySnakeCase, ToSnakeCase};
use phoxal::artifact::document::{RobotDocument, ServiceSelection, ServiceSource};
use prost_reflect::{DescriptorPool, MessageDescriptor};

use crate::project::error::Error;
use crate::project::{SelectedService, SourceSelection};

pub(crate) const DIRECTORY: &str = ".phoxal/robot-api";
pub(crate) const DEPENDENCY_KEY: &str = "robot_api";
const PHOXAL_VERSION: &str = "=0.0.0-dev.2";

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Candidate {
    pub package: String,
    pub manifest: String,
    pub lib: String,
    pub contracts: String,
    pub services: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct DependencySpec {
    instance: String,
    alias: String,
    package: String,
    fields: Vec<(&'static str, String)>,
}

#[derive(Debug, Default)]
struct ContractModule {
    reexport_path: Option<String>,
    children: BTreeMap<String, ContractModule>,
}

pub(crate) fn candidate(document: &RobotDocument, robot_root: &Path) -> Result<Candidate, Error> {
    let RobotDocument::V0 {
        robot, services, ..
    } = document;
    let package = format!("{}-api", robot.id.replace('_', "-"));
    let generated_root = robot_root.join(DIRECTORY);
    let mut dependencies = Vec::with_capacity(services.len());
    let mut normalized = BTreeMap::<String, String>::new();
    for (instance, selection) in services {
        let module = instance.to_snake_case();
        if let Some(previous) = normalized.insert(module.clone(), instance.clone()) {
            return Err(Error::ManifestPreparation {
                path: robot_root.join("robot.yaml"),
                message: format!(
                    "service instances `{previous}` and `{instance}` both normalize to Rust module `{module}`"
                ),
            });
        }
        dependencies.push(dependency_spec(
            instance,
            selection,
            robot_root,
            &generated_root,
        )?);
    }

    let mut manifest = format!(
        "# @generated by cargo-phoxal; do not edit.\n[package]\nname = {}\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n\n[lib]\npath = \"src/lib.rs\"\n\n[dependencies]\n",
        toml_string(&package)
    );
    if inherits_workspace_phoxal(robot_root) {
        manifest.push_str(
            "phoxal = { workspace = true, default-features = false, features = [\"contract\"] }\n",
        );
    } else {
        manifest.push_str(&format!(
            "phoxal = {{ version = {}, registry = \"phoxal\", default-features = false, features = [\"contract\"] }}\n",
            toml_string(PHOXAL_VERSION)
        ));
    }
    for dependency in &dependencies {
        manifest.push_str(&dependency.alias);
        manifest.push_str(" = { package = ");
        manifest.push_str(&toml_string(&dependency.package));
        for (key, value) in &dependency.fields {
            manifest.push_str(", ");
            manifest.push_str(key);
            manifest.push_str(" = ");
            manifest.push_str(value);
        }
        manifest.push_str(", default-features = false }\n");
    }

    let mut lib = String::from(
        "// @generated by cargo-phoxal; do not edit.\n#![allow(clippy::all)]\npub mod contracts;\npub mod services;\n",
    );
    for dependency in &dependencies {
        lib.push_str("#[doc(hidden)]\npub use ");
        lib.push_str(&dependency.alias);
        lib.push_str(" as __");
        lib.push_str(&dependency.alias);
        lib.push_str(";\n");
    }

    let contracts = String::from(
        "// @generated by cargo-phoxal; do not edit.\n// Final contract re-exports are installed after Cargo resolves exact packages.\n",
    );
    let mut services_source = String::from(
        "// @generated by cargo-phoxal; do not edit.\n// Final instance bindings are installed after contract validation.\n",
    );
    for dependency in &dependencies {
        services_source.push_str("#[doc(hidden)]\npub mod ");
        services_source.push_str(&dependency.instance.to_snake_case());
        services_source.push_str(" {}\n");
    }

    Ok(Candidate {
        package,
        manifest,
        lib,
        contracts,
        services: services_source,
    })
}

pub(crate) fn finalized_candidate(
    document: &RobotDocument,
    robot_root: &Path,
    sources: &SourceSelection,
) -> Result<Candidate, Error> {
    let mut candidate = candidate(document, robot_root)?;
    let mut contract_root = ContractModule::default();
    let mut services = String::from("// @generated by cargo-phoxal; do not edit.\n");
    let mut package_owners = BTreeMap::<String, (String, String)>::new();

    for (instance, selected) in &sources.services {
        let alias = dependency_alias(instance);
        let package_root = package_root(selected)?;
        let descriptor_path = package_root.join("generated/phoxal-descriptors.bin");
        let descriptor_bytes =
            std::fs::read(&descriptor_path).map_err(|source| Error::ManifestPreparation {
                path: descriptor_path.clone(),
                message: format!("cannot read generated contract descriptors: {source}"),
            })?;
        let pool = DescriptorPool::decode(descriptor_bytes.as_slice()).map_err(|error| {
            Error::ManifestPreparation {
                path: descriptor_path.clone(),
                message: format!("generated contract descriptors are invalid: {error}"),
            }
        })?;
        let owned_services = pool
            .services()
            .filter(|service| owns_service(&package_root, service))
            .collect::<Vec<_>>();
        if owned_services.is_empty() {
            return Err(Error::ManifestPreparation {
                path: descriptor_path,
                message: "contract package exposes no generated owned service".to_owned(),
            });
        }

        for service in owned_services {
            let package_name = service.package_name().to_owned();
            let reexport_path = contract_reexport_path(&alias, &package_root, &package_name);
            if let Some((owner_package, owner_alias)) = package_owners.get(&package_name) {
                if owner_package != &selected.package_id {
                    return Err(Error::ManifestPreparation {
                        path: package_root.join("Cargo.toml"),
                        message: format!(
                            "Protobuf package `{package_name}` is owned by both `{owner_alias}` and `{alias}`"
                        ),
                    });
                }
            } else {
                insert_contract_reexport(&mut contract_root, &package_name, &reexport_path)?;
                package_owners.insert(
                    package_name.clone(),
                    (selected.package_id.clone(), alias.clone()),
                );
            }
            for method in service.methods() {
                for message in [method.input(), method.output()] {
                    let parent_file = message.parent_file();
                    let referenced_package = parent_file.package_name();
                    if referenced_package == "google.protobuf" {
                        continue;
                    }
                    insert_contract_reexport(
                        &mut contract_root,
                        referenced_package,
                        &contract_reexport_path(&alias, &package_root, referenced_package),
                    )?;
                }
            }
            emit_instance_service(
                &mut services,
                instance,
                &alias,
                &service,
                &pool,
                &package_root,
            )?;
        }
    }
    let mut contracts = String::from("// @generated by cargo-phoxal; do not edit.\n");
    emit_contract_modules(&mut contracts, &contract_root, 0);
    candidate.contracts = contracts;
    candidate.services = format_generated_rust(&services)?;
    Ok(candidate)
}

fn format_generated_rust(source: &str) -> Result<String, Error> {
    let syntax = syn::parse_file(source).map_err(|error| Error::ManifestPreparation {
        path: PathBuf::from(DIRECTORY).join("src/services.rs"),
        message: format!("generated robot API is not valid Rust: {error}"),
    })?;
    Ok(format!(
        "// @generated by cargo-phoxal; do not edit.\n{}",
        prettyplease::unparse(&syntax)
    ))
}

pub(crate) fn package_root(service: &SelectedService) -> Result<PathBuf, Error> {
    if let crate::project::PackageSource::Local { manifest_path } = &service.source {
        return manifest_path
            .parent()
            .map(Path::to_path_buf)
            .ok_or_else(|| Error::ManifestPreparation {
                path: manifest_path.clone(),
                message: "service manifest has no package directory".to_owned(),
            });
    }
    let mut cursor = service.library.source_path.parent();
    while let Some(path) = cursor {
        if path.join("generated/phoxal-descriptors.bin").is_file() {
            return Ok(path.to_owned());
        }
        cursor = path.parent();
    }
    Err(Error::ManifestPreparation {
        path: service.library.source_path.clone(),
        message: "resolved contract package has no generated descriptor artifact".to_owned(),
    })
}

fn insert_contract_reexport(
    root: &mut ContractModule,
    package: &str,
    reexport_path: &str,
) -> Result<(), Error> {
    let mut node = root;
    for module in package.split('.') {
        let module = module.to_snake_case();
        if module.is_empty() {
            return Err(Error::ManifestPreparation {
                path: PathBuf::from("generated/phoxal-descriptors.bin"),
                message: format!("Protobuf package `{package}` has an empty module segment"),
            });
        }
        node = node.children.entry(module).or_default();
    }
    if let Some(previous) = &node.reexport_path
        && previous != reexport_path
    {
        return Err(Error::ManifestPreparation {
            path: PathBuf::from("generated/phoxal-descriptors.bin"),
            message: format!(
                "Protobuf package `{package}` maps to generated paths `{previous}` and `{reexport_path}`"
            ),
        });
    }
    node.reexport_path = Some(reexport_path.to_owned());
    Ok(())
}

fn emit_contract_modules(output: &mut String, node: &ContractModule, depth: usize) {
    if let Some(reexport_path) = &node.reexport_path {
        output.push_str(&"    ".repeat(depth));
        output.push_str("pub use ");
        output.push_str(reexport_path);
        output.push_str("::*;\n");
    }
    for (module, child) in &node.children {
        output.push_str(&"    ".repeat(depth));
        output.push_str("pub mod ");
        output.push_str(module);
        output.push_str(" {\n");
        emit_contract_modules(output, child, depth + 1);
        output.push_str(&"    ".repeat(depth));
        output.push_str("}\n");
    }
}

fn emit_instance_service(
    output: &mut String,
    instance: &str,
    alias: &str,
    service: &prost_reflect::ServiceDescriptor,
    pool: &DescriptorPool,
    package_root: &Path,
) -> Result<(), Error> {
    output.push_str("pub mod ");
    output.push_str(&instance.to_snake_case());
    output.push_str(" {\n");
    let service_module = service.name().to_snake_case();
    let lease = pool.get_extension_by_name("phoxal.api.lease");
    for method in service.methods() {
        let function = method.name().to_snake_case();
        let constant = method.name().to_shouty_snake_case();
        let method_path = format!("crate::__{alias}::{service_module}::methods::{constant}");
        let request = rust_message_path(&method.input(), alias, package_root);
        let response = rust_message_path(&method.output(), alias, package_root);
        if method.is_client_streaming() {
            return Err(Error::ManifestPreparation {
                path: PathBuf::from("generated/phoxal-descriptors.bin"),
                message: format!("{} uses unsupported client streaming", method.full_name()),
            });
        }
        if method.is_server_streaming() {
            if method.input().full_name() != "google.protobuf.Empty" {
                return Err(Error::ManifestPreparation {
                    path: PathBuf::from("generated/phoxal-descriptors.bin"),
                    message: format!(
                        "{} is streaming but does not accept google.protobuf.Empty",
                        method.full_name()
                    ),
                });
            }
            output.push_str(&format!(
                "    #[must_use]\n    pub fn {function}() -> ::phoxal::contract::Observation<{response}> {{\n        use {method_path} as METHOD;\n        METHOD.bind({instance:?})\n    }}\n"
            ));
        } else {
            output.push_str(&format!(
                "    #[must_use]\n    pub fn {function}(request: {request}) -> ::phoxal::contract::Call<{request}, {response}> {{\n        use {method_path} as METHOD;\n        METHOD.bind({instance:?}, request)\n    }}\n"
            ));
            if lease
                .as_ref()
                .is_some_and(|extension| method.options().has_extension(extension))
            {
                output.push_str(&format!(
                    "    #[must_use]\n    pub fn withdraw_{function}() -> ::phoxal::contract::Withdraw<{request}, {response}> {{\n        use {method_path} as METHOD;\n        METHOD.withdraw({instance:?})\n    }}\n"
                ));
            }
        }
    }
    output.push_str("}\n");
    Ok(())
}

fn rust_message_path(message: &MessageDescriptor, alias: &str, package_root: &Path) -> String {
    if message.full_name() == "google.protobuf.Empty" {
        return "::phoxal::contract::Empty".to_owned();
    }
    let parent_file = message.parent_file();
    let package = parent_file.package_name();
    let relative = message
        .full_name()
        .strip_prefix(package)
        .and_then(|name| name.strip_prefix('.'))
        .unwrap_or_else(|| message.name());
    let mut pieces = relative.split('.').collect::<Vec<_>>();
    let message_name = pieces.pop().unwrap_or_else(|| message.name());
    let mut path = contract_reexport_path(alias, package_root, package);
    for enclosing in pieces {
        path.push_str("::");
        path.push_str(&enclosing.to_snake_case());
    }
    path.push_str("::");
    path.push_str(message_name);
    path
}

fn contract_reexport_path(alias: &str, package_root: &Path, package: &str) -> String {
    if generated_package_owns_methods(package_root, package) {
        format!("crate::__{alias}")
    } else {
        format!("crate::__{alias}::{}", contract_import_module(package))
    }
}

fn owns_service(package_root: &Path, service: &prost_reflect::ServiceDescriptor) -> bool {
    let path = package_root.join(format!("generated/{}.rs", service.package_name()));
    let Ok(source) = std::fs::read_to_string(path) else {
        return false;
    };
    source.contains(&format!("pub mod {} {{", service.name().to_snake_case()))
        && source.contains("pub mod methods {")
}

fn generated_package_owns_methods(package_root: &Path, package: &str) -> bool {
    std::fs::read_to_string(package_root.join(format!("generated/{package}.rs")))
        .is_ok_and(|source| source.contains("pub mod methods {"))
}

fn contract_import_module(package: &str) -> String {
    let mut module = String::from("__phoxal_contract_import_");
    for character in package.trim_start_matches('.').chars() {
        if character.is_ascii_alphanumeric() {
            module.push(character.to_ascii_lowercase());
        } else {
            module.push('_');
        }
    }
    module
}

fn dependency_spec(
    instance: &str,
    selection: &ServiceSelection,
    robot_root: &Path,
    generated_root: &Path,
) -> Result<DependencySpec, Error> {
    match &selection.source {
        Some(ServiceSource::Path(source)) => {
            let selected = robot_root.join(&source.path);
            let manifest = selected.join("Cargo.toml");
            let package = package_name(&manifest)?;
            let relative = relative_path(generated_root, &selected).ok_or_else(|| {
                Error::ManifestPreparation {
                    path: robot_root.join("robot.yaml"),
                    message: format!(
                        "cannot express local service source {} relative to generated robot_api",
                        selected.display()
                    ),
                }
            })?;
            Ok(DependencySpec {
                instance: instance.to_owned(),
                alias: dependency_alias(instance),
                package,
                fields: vec![("path", toml_string(&relative.to_string_lossy()))],
            })
        }
        Some(ServiceSource::Git(source)) => Ok(DependencySpec {
            instance: instance.to_owned(),
            alias: dependency_alias(instance),
            package: source.package.clone(),
            fields: vec![
                ("git", toml_string(&source.git)),
                ("rev", toml_string(&source.rev)),
            ],
        }),
        Some(ServiceSource::Registry(source)) => Ok(DependencySpec {
            instance: instance.to_owned(),
            alias: dependency_alias(instance),
            package: source.registry.clone(),
            fields: vec![
                ("version", toml_string(&source.version)),
                ("registry", toml_string("phoxal")),
            ],
        }),
        None => Ok(DependencySpec {
            instance: instance.to_owned(),
            alias: dependency_alias(instance),
            package: official_package(instance),
            fields: vec![
                ("version", toml_string(PHOXAL_VERSION)),
                ("registry", toml_string("phoxal")),
            ],
        }),
    }
}

fn package_name(manifest: &Path) -> Result<String, Error> {
    let text = std::fs::read_to_string(manifest).map_err(|source| Error::ReadManifest {
        path: manifest.to_owned(),
        source,
    })?;
    let document =
        text.parse::<toml_edit::DocumentMut>()
            .map_err(|error| Error::ManifestPreparation {
                path: manifest.to_owned(),
                message: format!("service Cargo.toml is invalid: {error}"),
            })?;
    document["package"]["name"]
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| Error::ManifestPreparation {
            path: manifest.to_owned(),
            message: "local service Cargo.toml has no package.name".to_owned(),
        })
}

fn dependency_alias(instance: &str) -> String {
    format!("service_{}", instance.to_snake_case())
}

fn official_package(instance: &str) -> String {
    format!("phoxal-service-{instance}")
}

fn inherits_workspace_phoxal(robot_root: &Path) -> bool {
    robot_root.ancestors().any(|root| {
        let manifest = root.join("Cargo.toml");
        let Ok(text) = std::fs::read_to_string(manifest) else {
            return false;
        };
        let Ok(document) = text.parse::<toml_edit::DocumentMut>() else {
            return false;
        };
        document
            .get("workspace")
            .and_then(toml_edit::Item::as_table)
            .and_then(|workspace| workspace.get("dependencies"))
            .and_then(toml_edit::Item::as_table)
            .is_some_and(|dependencies| dependencies.contains_key("phoxal"))
    })
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_owned()).to_string()
}

fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from = lexical_components(from);
    let to = lexical_components(to);
    let common = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();
    if common == 0 && from.first() != to.first() {
        return None;
    }
    let mut result = PathBuf::new();
    for _ in common..from.len() {
        result.push("..");
    }
    for component in &to[common..] {
        result.push(component);
    }
    Some(result)
}

fn lexical_components(path: &Path) -> Vec<String> {
    let mut result = Vec::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                let _ = result.pop();
            }
            Component::RootDir => result.push(String::from("/")),
            Component::Prefix(prefix) => result.push(prefix.as_os_str().to_string_lossy().into()),
            Component::Normal(value) => result.push(value.to_string_lossy().into()),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn candidate_is_robot_qualified_and_uses_only_generated_service_dependencies() {
        let directory = tempfile::tempdir().expect("temporary project");
        let service = directory.path().join("motion-local");
        fs::create_dir_all(&service).expect("service directory");
        fs::write(
            service.join("Cargo.toml"),
            "[package]\nname = \"acme-motion\"\nversion = \"0.1.0\"\n",
        )
        .expect("service manifest");
        let document: RobotDocument = serde_yaml::from_str(
            r#"
schema: phoxal/robot/v0
robot:
  id: warehouse_rover
  model: model.xml
services:
  motion-dev:
    source:
      path: motion-local
  mapping:
    source:
      registry: acme-mapping
      version: "0.3"
"#,
        )
        .expect("robot document");

        let candidate = candidate(&document, directory.path()).expect("candidate");
        assert_eq!(candidate.package, "warehouse-rover-api");
        assert!(candidate.manifest.contains("service_motion_dev"));
        assert!(candidate.manifest.contains("package = \"acme-motion\""));
        assert!(candidate.manifest.contains("path = \"../../motion-local\""));
        assert!(candidate.manifest.contains("package = \"acme-mapping\""));
        assert!(candidate.services.contains("pub mod motion_dev"));
    }

    #[test]
    fn normalized_instance_collisions_fail_generation() {
        let document: RobotDocument = serde_yaml::from_str(
            r#"
schema: phoxal/robot/v0
robot:
  id: rover
  model: model.xml
services:
  motion-dev: {}
  motion_dev: {}
"#,
        )
        .expect("robot document");
        let error = candidate(&document, Path::new("/tmp/rover")).expect_err("collision");
        assert!(error.to_string().contains("both normalize"));
    }

    #[test]
    fn contract_reexports_merge_shared_package_prefixes() {
        let mut root = ContractModule::default();
        insert_contract_reexport(&mut root, "phoxal.motion.v1", "crate::__service_motion")
            .expect("motion package");
        insert_contract_reexport(&mut root, "phoxal.world.v1", "crate::__service_world")
            .expect("world package");
        let mut output = String::new();
        emit_contract_modules(&mut output, &root, 0);

        assert_eq!(output.matches("pub mod phoxal").count(), 1);
        assert!(output.contains("pub mod motion"));
        assert!(output.contains("pub mod world"));
        assert!(output.contains("pub use crate::__service_motion::*;"));
        assert!(output.contains("pub use crate::__service_world::*;"));
    }
}
