[package]
name = "phoxal-runtime-odometry"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
phoxal = { workspace = true, features = ["scenario"] }

async-trait = { workspace = true }
urdf-rs = { workspace = true }

anyhow = { workspace = true }
nalgebra = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
approx = "0.5.1"
