[package]
name = "phoxal-service-follow"
version = "0.19.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = true
description = "Phoxal official service: follow - pure-pursuit path follower."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-follow"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
