[package]
name = "phoxal-component-oak_d_lite"
version = "0.0.0-dev.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: oak_d_lite - camera/depth/IMU."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["api/**", "build.rs", "src/**", "Cargo.toml", "Cargo.lock", "component.yaml", "model.xml", "LICENSE", "README.md"]

[[bin]]
name = "phoxal-component-oak_d_lite"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = ["runtime"]
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["contract"] }
anyhow = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[build-dependencies]
phoxal = { workspace = true, default-features = false, features = ["build"] }

[lints]
workspace = true
