[package]
name = "phoxal-component-oak_d_lite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official driver: oak_d_lite - camera/depth/IMU."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-component-oak_d_lite"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
