//! The external simulation hand-off: the authoritative world clock.
//!
//! The endpoint is deliberately an `Event`: the hand is stamped at a completed
//! world step, and its ordered stream transport preserves every accepted clock
//! and reports gaps instead of silently coalescing them.

/// The body carried by the authoritative simulation clock hand.
///
/// The production timeline and exact instant are bus metadata. The body carries
/// only the simulator's monotonic step counter.
#[derive(
    phoxal_macros::DescribeWire,
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    serde::Serialize,
    serde::Deserialize,
)]
pub struct Clock {
    pub step: u64,
}

// The world-clock marker is a sibling of `StateContract`, never generated by a
// semantic descriptor: it is what keeps the ordinary state publisher from
// minting world steps, so only the world-authority-gated publisher can take
// this endpoint.
impl ::phoxal_bus::WorldClockContract
    for crate::runtime::endpoint::simulation::ClockEndpoint
{
}
