[package]
name = "phoxal-service-localize"
version = "0.19.9"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official service: localize - odometry-anchored localization estimate."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-localize"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true, features = ["preview-v2"] }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
