[package]
name = "phoxal-component-bno085"
version = "0.0.0-dev.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: bno085 - IMU."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["src/**", "build.rs", "Cargo.toml", "Cargo.lock", "component.yaml", "model.xml", "LICENSE", "README.md"]

[[bin]]
name = "phoxal-component-bno085"
path = "src/main.rs"

[build-dependencies]
phoxal = { workspace = true, default-features = false, features = ["build"] }

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["runtime"] }
anyhow.workspace = true
serde.workspace = true

[lints]
workspace = true
