[package]
name = "phoxal-component-bno085"
version = "0.0.0-dev.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: bno085 - IMU."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["generated/**", "src/**", "proto/**", "Cargo.toml", "component.yaml", "model.xml"]

[lib]
name = "phoxal_component_bno085"
path = "generated/lib.rs"

[[bin]]
name = "phoxal-component-bno085"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = []
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["contract"] }
anyhow = { workspace = true, optional = true }
prost = { workspace = true }
serde = { workspace = true, optional = true }

[package.metadata.phoxal.contract]
protos = ["proto/phoxal/component/bno085/v1/bno085.proto"]
includes = ["proto"]
generated = "generated"

[lints]
workspace = true
