[package]
name = "phoxal-driver-zed_f9p"
version = "0.1.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official driver: zed_f9p - GNSS."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-driver-zed_f9p"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
