[package]
name = "phoxal-component-zed_f9p"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: zed_f9p - GNSS."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-component-zed_f9p"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
