[package]
name = "phoxal-component-ddsm115"
version = "0.1.7"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official driver: ddsm115 - wheel hub motor."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-component-ddsm115"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true, features = ["preview-v2"] }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
