[package]
name = "phoxal-service-presence"
version = "0.19.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = true
description = "Phoxal official service: presence - participant heartbeat aggregation."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-presence"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
