[package]
name = "phoxal-component-zed_f9p"
version = "0.0.0-dev.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: zed_f9p - GNSS."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["build.rs", "src/**", "proto/**", "Cargo.toml", "component.yaml", "model.xml"]

[lib]
name = "phoxal_component_zed_f9p"
path = "src/lib.rs"

[[bin]]
name = "phoxal-component-zed_f9p"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = ["runtime"]
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["port"] }
anyhow = { workspace = true, optional = true }
prost = { workspace = true }
serde = { workspace = true, optional = true }

[build-dependencies]
phoxal = { workspace = true, default-features = false, features = ["build"] }

[lints]
workspace = true
