[package]
name = "phoxal-component-vl53l1x"
version = "0.68.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: vl53l1x - range/time-of-flight."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["build.rs", "src/**", "proto/**", "Cargo.toml", "component.yaml", "model.xml"]

[package.metadata.phoxal]
kind = "component"

[lib]
name = "phoxal_component_vl53l1x"
path = "src/lib.rs"

[[bin]]
name = "phoxal-component-vl53l1x"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true, features = ["participant"] }
anyhow = { workspace = true }
phoxal-port = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }

[build-dependencies]
phoxal-build = { workspace = true }

[lints]
workspace = true
