[package]
name = "phoxal-component-vl53l1x"
version = "0.0.0-dev.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: vl53l1x - range/time-of-flight."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["generated/**", "src/**", "proto/**", "Cargo.toml", "component.yaml", "model.xml"]

[lib]
name = "phoxal_component_vl53l1x"
path = "generated/lib.rs"

[[bin]]
name = "phoxal-component-vl53l1x"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = []
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["contract", "robotics"] }
anyhow = { workspace = true, optional = true }
prost = { workspace = true }
serde = { workspace = true, optional = true }

[package.metadata.phoxal.contract]
protos = ["proto/phoxal/component/vl53l1x/v1/vl53l1x.proto"]
includes = ["proto"]
generated = "generated"
dependencies = [
    { dependency = "phoxal", proto_package = ".phoxal.robotics.v1", rust_path = "::phoxal::robotics" },
]

[lints]
workspace = true
