[package]
name = "phoxal-runtime-asset"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official runtime: asset — serves bundle assets over the bus."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-runtime-asset"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }

[lints]
workspace = true
