[package]
name = "example-robot-beta"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "AGPL-3.0-only"
description = "The second robot package in the multiple-robot example."

[dependencies]
phoxal = { path = "../../../../phoxal", version = "=0.0.0-dev.1", default-features = false, features = ["runtime"] }
phoxal-supervisor = { path = "../../../../supervisor", version = "=0.0.0-dev.1" }

[lints]
workspace = true
