[package]
name = "phoxal-tool-joypad"
version = "0.1.12"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official tool: joypad - minimal gamepad teleop bridge."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.phoxal]
unsupported-targets = ["*-musl"]

[[bin]]
name = "phoxal-tool-joypad"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
gilrs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
