[package]
name = "phoxal-tool-joypad"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = true
description = "Phoxal official tool: joypad - minimal gamepad teleop bridge."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-tool-joypad"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }
gilrs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
