[package]
name = "phoxal-navigation"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Public navigation service contract for Phoxal."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["build.rs", "src/**", "proto/**", "Cargo.toml", "README.md"]

[dependencies]
phoxal-port = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
phoxal-build = { workspace = true }

[lints]
workspace = true
