//! Shared test fixtures. No tests live here - every test lives with the module
//! whose behavior it exercises.
//!
//! What this module owns is the *stand-in contract tree*: a hand-written
//! [`ApiVersion`] and its bodies. `phoxal-bus` is the ABI floor and must be
//! testable without the concrete API versions, which are generated by
//! `phoxal_api_tree!` in the downstream `phoxal-api` crate. Several modules
//! (`abi`, `handle`, `session`, `server`, `router`) need the *same* stand-in
//! bodies to exercise a real end-to-end path, so they are declared once rather
//! than five times.
//!
//! The golden tests that bind the bus to the real generated tree live in the
//! `phoxal` crate.

use phoxal_runtime_contract::identity::{ExecutionId, ParticipantId, ProducerId, TimelineId};
use serde::{Deserialize, Serialize};
use zenoh::key_expr::KeyExpr;
use zenoh::sample::{Sample, SampleBuilder};

use crate::abi::CodecId;
use crate::contract::{
    ApiVersion, CommandContract, ContractBody, DeliveryFamily, StateContract, TopicRole,
};
use crate::handle::stamp::StepToken;
use crate::metadata::{BusMetadata, ParticipantSourceIdentity, SourceAttribution};
use crate::session::BusConfig;
use crate::time::{RobotInstant, TimeWindow};

/// The stand-in api tree. The bus client is generic over [`ApiVersion`] and
/// [`ContractBody`]; that is all it needs to be exercised end to end.
pub(crate) enum TestApi {}

impl ApiVersion for TestApi {
    const ID: &'static str = "yTEST";
}

/// A state body: it is published at a logical step, so it carries robot time
/// and is subject to timeline barriers.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct Target {
    pub(crate) linear_x_mps: f32,
    pub(crate) angular_z_radps: f32,
}

impl ContractBody for Target {
    type Api = TestApi;
    const NAME: &'static str = "yTEST::drive::Target";
    const VERSION: &'static str = "yTEST";
    const CONTRACT: &'static str = "drive::Target";
    const TOPIC: &'static str = "yTEST/drive/target";
    const ROLE: TopicRole = TopicRole::State;
    const DELIVERY: DeliveryFamily = DeliveryFamily::State;
}

impl StateContract for Target {}

/// A command body, standing in for a leased control input: it expresses no
/// robot time, so it is never quarantined at a timeline barrier.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct Manual {
    pub(crate) linear_x_mps: f32,
}

impl ContractBody for Manual {
    type Api = TestApi;
    const NAME: &'static str = "yTEST::motion::Manual";
    const VERSION: &'static str = "yTEST";
    const CONTRACT: &'static str = "motion::Manual";
    const TOPIC: &'static str = "yTEST/motion/manual";
    const ROLE: TopicRole = TopicRole::Command;
    const DELIVERY: DeliveryFamily = DeliveryFamily::Setpoint;
}

impl CommandContract for Manual {}

/// The request half of a stand-in query contract.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct GetRequest {
    pub(crate) path: String,
}

impl ContractBody for GetRequest {
    type Api = TestApi;
    const NAME: &'static str = "yTEST::asset::GetRequest";
    const VERSION: &'static str = "yTEST";
    const CONTRACT: &'static str = "asset::GetRequest";
    const TOPIC: &'static str = "yTEST/asset/get";
    const ROLE: TopicRole = TopicRole::Query;
    const DELIVERY: DeliveryFamily = DeliveryFamily::Query;
}

/// The response half of a stand-in query contract.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) enum GetResponse {
    Found { bytes: Vec<u8> },
    Missing,
}

impl ContractBody for GetResponse {
    type Api = TestApi;
    const NAME: &'static str = "yTEST::asset::GetResponse";
    const VERSION: &'static str = "yTEST";
    const CONTRACT: &'static str = "asset::GetResponse";
    const TOPIC: &'static str = "yTEST/asset/get";
    const ROLE: TopicRole = TopicRole::Query;
    const DELIVERY: DeliveryFamily = DeliveryFamily::Query;
}

/// A named test timeline. Production timelines are minted opaquely, so tests
/// that need to talk about a *specific* world history name theirs.
pub(crate) fn timeline(value: u64) -> TimelineId {
    TimelineId::from_raw(value).expect("a test timeline id is nonzero")
}

/// A distinct test producer. Nothing mints a producer in production - a
/// session's identity is the session - so tests name theirs explicitly.
pub(crate) fn producer(value: u128) -> ProducerId {
    ProducerId::try_from((1_u128 << 124) | value).expect("a test producer is canonical")
}

/// A participant config for an in-process unit-test fabric.
pub(crate) fn participant_config(participant: impl Into<String>) -> BusConfig {
    BusConfig::for_participant(
        ExecutionId::mint(),
        ParticipantId::new(participant).expect("valid test participant"),
        Vec::new(),
    )
}

/// A step token on a named timeline.
pub(crate) fn step(line: u64, ticks: u64) -> StepToken {
    StepToken::mint(RobotInstant::new(timeline(line), ticks))
}

/// Provenance for a hand-built sample.
pub(crate) fn metadata() -> BusMetadata {
    BusMetadata {
        codec: CodecId::MessagePack.as_u8(),
        sequence: 7,
        produced_at: Some(TimeWindow::exact(RobotInstant::new(timeline(1), 42))),
        source: SourceAttribution::Participant(ParticipantSourceIdentity::new(
            phoxal_runtime_contract::identity::ParticipantId::new("tester")
                .expect("test participant"),
            producer(1),
        )),
    }
}

/// A sample carrying `payload`, whose encoding string and attachment both name
/// `codec`.
pub(crate) fn sample_with(codec: u8, payload: Vec<u8>) -> Sample {
    let encoding = if codec == CodecId::MessagePack.as_u8() {
        CodecId::MessagePack.encoding_string()
    } else {
        format!("phoxal/v0;codec={codec}")
    };
    sample_with_encoding(codec, encoding, payload)
}

/// A sample whose encoding string and attachment codec are set independently,
/// so a test can make the two disagree.
pub(crate) fn sample_with_encoding(codec: u8, encoding: String, payload: Vec<u8>) -> Sample {
    let mut meta = metadata();
    meta.codec = codec;
    let key: KeyExpr<'static> =
        KeyExpr::try_from("phoxal/dead/yTEST/drive/target").expect("a legal test key");
    SampleBuilder::put(key, payload)
        .encoding(encoding)
        .attachment(meta.encode().expect("test metadata encodes"))
        .into()
}

/// A well-formed [`Target`] sample under `codec`.
pub(crate) fn sample(codec: u8) -> Sample {
    let payload = rmp_serde::to_vec_named(&Target {
        linear_x_mps: 1.0,
        angular_z_radps: 0.5,
    })
    .expect("a test body encodes");
    sample_with(codec, payload)
}

/// A short unix-socket endpoint plus the directory that owns it.
///
/// Unix-socket addresses are length-limited and the macOS default temp dir is
/// long enough to overflow the limit, so these bind under `/tmp` directly.
#[cfg(feature = "router")]
pub(crate) fn socket_endpoint(prefix: &str) -> (tempfile::TempDir, String) {
    let dir = tempfile::Builder::new()
        .prefix(prefix)
        .tempdir_in("/tmp")
        .expect("short-path temp dir for the unix socket");
    let endpoint = format!("unixsock-stream/{}", dir.path().join("r.sock").display());
    (dir, endpoint)
}
