[package]
name = "phoxal-service-kinematics"
version = "0.0.0-dev.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal kinematics service executable and packaged API."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["src/**", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE"]

[[bin]]
name = "phoxal-service-kinematics"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["runtime"] }
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true

[lints]
workspace = true
