[package]
name = "phoxal-runtime-frame"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
phoxal = { workspace = true, features = ["scenario"] }
urdf-rs = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync", "signal", "process", "time"] }
tracing = { workspace = true }
nalgebra = { workspace = true }
