//! Generated scenario harness source.
//!
//! The tool writes `<robot-root>/.phoxal/generated/scenarios/main.rs`
//! from [`generate_harness_source`]. The generated file is the `main`
//! entry point for the `phoxal-scenarios` test target the preparation
//! step adds to the robot's Cargo.toml.
//!
//! Each discovered scenario becomes one private module via `include!`,
//! which inlines the user's scenario source into the harness compilation
//! unit. The `inventory::submit!` calls in those sources therefore
//! register the scenarios into the static
//! [`phoxal::scenario::ScenarioRegistry`] that the harness queries.
//!
//! The generated harness binary depends only on the
//! SDK; the tool drives the lifecycle over a private control channel
//! that the harness speaks through `phoxal::scenario::__harness`. No
//! project compiler import is present in the generated source.

use std::fmt::Write as _;
use std::path::Path;

/// Build the generated harness source. The `robot_root` is the path the
/// generated `include!` directives are relative to. The returned string
/// is the complete `main.rs` content ready to be written under
/// `<robot_root>/.phoxal/generated/scenarios/main.rs`.
pub fn generate_harness_source(
    robot_root: &Path,
    discovered: &[super::discovery::DiscoveredScenario],
) -> String {
    let mut source = String::new();
    source.push_str("// AUTO-GENERATED by cargo phoxal simulation scenario list/run.\n");
    source.push_str("// Do not edit: this file is regenerated on every preparation.\n");
    source.push_str("#![allow(dead_code, non_camel_case_types)]\n\n");

    // Each discovered scenario becomes one private module via a
    // `#[path = "..."] mod name;` declaration so the user's scenario
    // source becomes the module body. Without the trailing semicolon the
    // path attribute is silently dropped and the module is empty; the
    // user's `inventory::submit!` calls then never reach the linker.
    for scenario in discovered {
        let abs = robot_root.join(&scenario.relative_path);
        let include_path = match abs.strip_prefix(robot_root) {
            Ok(rel) => rel.to_string_lossy().replace('\\', "/"),
            Err(_) => abs.to_string_lossy().replace('\\', "/"),
        };
        // `writeln!` into a `String` cannot fail under any of the
        // standard library implementations, but `clippy::expect_used`
        // denies `.expect()` regardless. `let _ = ...` consumes the
        // result without surfacing a panic path.
        let _ = writeln!(
            source,
            "#[path = \"../../../{include_path}\"]\nmod {ident};",
            include_path = include_path,
            ident = scenario.module_identifier,
        );
    }

    // The `main` is a minimal dispatch that prints the registered
    // scenarios and forwards a `run <name>` invocation to the case
    // host over the private control channel. The case host is owned
    // by the cargo-phoxal project implementation
    // (`tools/cargo-phoxal/src/project/scenario/case_host.rs`) and
    // owns the simulation lifecycle (provisioning, supervisor
    // admission, native completion, bounded cleanup, lifecycle-owned
    // terminal evidence). The harness binary depends only on the SDK;
    // the tool drives the protocol through
    // `phoxal::scenario::__harness`. The harness retains the planned
    // scenario instance and runs `verify_box` on it after the tool
    // sends the lifecycle-observed evidence; the tool only reports
    // success when lifecycle, evidence validation, and author
    // verification all succeed.
    source.push_str(
        r#"fn main() -> phoxal::Result<()> {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(String::as_str).unwrap_or("list") {
        "list" => {
            let scenarios =
                phoxal::scenario::list_scenarios().map_err(|e| phoxal::anyhow!("{e}"))?;
            for s in scenarios {
                println!("{}\t{}", s.name, s.module_path);
            }
            Ok(())
        }
        "run" => {
            let name = args
                .get(2)
                .ok_or_else(|| phoxal::anyhow!("usage: phoxal-scenarios run <name>"))?;
            // The tool pre-positions two file descriptors in the
            // environment (PHOXAL_HARNESS_CTL_IN / _OUT) before
            // launching this binary. The SDK's hidden __harness
            // module reads them and walks the eight-step protocol.
            phoxal::scenario::__harness::run_harness_case(name)
                .map_err(|e| phoxal::anyhow!("scenario `{name}` case host failed: {e:#}"))
        }
        _ => Err(phoxal::anyhow!(
            "usage: phoxal-scenarios [list | run <name>]"
        )),
    }
}
"#,
    );
    source
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn generated_source_includes_each_scenario() {
        let root = PathBuf::from("/tmp/example-robot");
        let discovered = vec![
            super::super::discovery::DiscoveredScenario {
                relative_path: PathBuf::from("scenarios/forward_turn_stop.rs"),
                module_identifier: "_scenario_forward_turn_stop".to_owned(),
            },
            super::super::discovery::DiscoveredScenario {
                relative_path: PathBuf::from("scenarios/from_mod/mod.rs"),
                module_identifier: "_scenario_from_mod".to_owned(),
            },
        ];
        let src = generate_harness_source(&root, &discovered);
        assert!(src.contains("mod _scenario_forward_turn_stop"));
        assert!(src.contains("mod _scenario_from_mod"));
        assert!(src.contains("scenarios/forward_turn_stop.rs"));
        assert!(src.contains("scenarios/from_mod/mod.rs"));
        assert!(src.contains("fn main() -> phoxal::Result<()>"));
    }
}
