//! Generated scenario harness source.
//!
//! The tool writes `<robot-root>/.phoxal/generated/scenarios/main.rs`
//! from [`generate_harness_source`]. The generated file is the `main`
//! entry point for the `phoxal-scenarios` test target the preparation
//! step adds to the robot's Cargo.toml.
//!
//! Each discovered scenario becomes one private module via `include!`,
//! which inlines the user's scenario source into the harness compilation
//! unit. The `inventory::submit!` calls in those sources therefore
//! register the scenarios into the static
//! [`phoxal::scenario::ScenarioRegistry`] that the harness queries.

use std::fmt::Write as _;
use std::path::Path;

/// Build the generated harness source. The `robot_root` is the path the
/// generated `include!` directives are relative to. The returned string
/// is the complete `main.rs` content ready to be written under
/// `<robot_root>/.phoxal/generated/scenarios/main.rs`.
pub fn generate_harness_source(
    robot_root: &Path,
    discovered: &[super::discovery::DiscoveredScenario],
) -> String {
    let mut source = String::new();
    source.push_str("// AUTO-GENERATED by cargo phoxal simulation scenario list/run.\n");
    source.push_str("// Do not edit: this file is regenerated on every preparation.\n");
    source.push_str("#![allow(dead_code, non_camel_case_types)]\n\n");

    // Each discovered scenario becomes one private module via a
    // `#[path = "..."] mod name;` declaration so the user's scenario
    // source becomes the module body. Without the trailing semicolon the
    // path attribute is silently dropped and the module is empty; the
    // user's `inventory::submit!` calls then never reach the linker.
    for scenario in discovered {
        let abs = robot_root.join(&scenario.relative_path);
        let include_path = match abs.strip_prefix(robot_root) {
            Ok(rel) => rel.to_string_lossy().replace('\\', "/"),
            Err(_) => abs.to_string_lossy().replace('\\', "/"),
        };
        // `writeln!` into a `String` cannot fail under any of the
        // standard library implementations, but `clippy::expect_used`
        // denies `.expect()` regardless. `let _ = ...` consumes the
        // result without surfacing a panic path.
        let _ = writeln!(
            source,
            "#[path = \"../../../{include_path}\"]\nmod {ident};\n",
            include_path = include_path,
            ident = scenario.module_identifier,
        );
    }

    // The `main` is a minimal dispatch that prints the registered
    // scenarios and forwards a `run <name>` invocation to the case
    // host. The case host lives in `phoxal_project::scenario::case_host`
    // and owns the simulation lifecycle (provisioning, supervisor
    // admission, native completion, bounded cleanup, lifecycle-owned
    // terminal evidence). The harness binary is the only place that
    // holds the planned scenario instance, so it owns the call to
    // `verify_box` on the retained instance after the case host
    // seals the run.
    source.push_str(
        r#"
fn main() -> phoxal::Result<()> {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(String::as_str).unwrap_or("list") {
        "list" => {
            let scenarios = phoxal::scenario::list_scenarios()
                .map_err(|e| phoxal::anyhow!("{e}"))?;
            for s in scenarios {
                println!("{}\t{}", s.name, s.module_path);
            }
            Ok(())
        }
        "run" => {
            let name = args
                .get(2)
                .ok_or_else(|| phoxal::anyhow!("usage: phoxal-scenarios run <name>"))?;
            run_scenario_case(name)
        }
        _ => Err(phoxal::anyhow!("usage: phoxal-scenarios [list | run <name>]")),
    }
}

fn run_scenario_case(name: &str) -> phoxal::Result<()> {
    let entries = phoxal::scenario::list_scenarios()
        .map_err(|e| phoxal::anyhow!("{e}"))?;
    let entry = entries
        .iter()
        .find(|e| e.short_name == name || e.name == name)
        .ok_or_else(|| phoxal::anyhow!("scenario `{name}` is not registered"))?;
    let planned = (entry.entry)()
        .map_err(|e| phoxal::anyhow!("scenario `{name}` planning failed: {e:#}"))?;

    let cargo_options = phoxal_project::CargoOptions::default();
    let run = phoxal_project::scenario::case_host::run_case_host(
        &planned,
        &cargo_options,
    )
    .map_err(|e| phoxal::anyhow!("scenario `{name}` case host failed: {e}"))?;

    // The seal-time `passed` flag is the precondition contract. The
    // case host enforces it before this point; an explicit check makes
    // the contract visible at the call site.
    if !run.passed() {
        return Err(phoxal::anyhow!(
            "scenario `{name}` case host sealed a non-passing run; verify is not invoked"
        ));
    }

    planned
        .scenario
        .verify_box(&run)
        .map_err(|e| phoxal::anyhow!("scenario `{name}` verify failed: {e:#}"))?;
    println!("scenario {}: PASSED", planned.name);
    Ok(())
}
"#,
    );
    source
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn generated_source_includes_each_scenario() {
        let root = PathBuf::from("/tmp/example-robot");
        let discovered = vec![
            super::super::discovery::DiscoveredScenario {
                relative_path: PathBuf::from("scenarios/forward_turn_stop.rs"),
                module_identifier: "_scenario_forward_turn_stop".to_owned(),
            },
            super::super::discovery::DiscoveredScenario {
                relative_path: PathBuf::from("scenarios/from_mod/mod.rs"),
                module_identifier: "_scenario_from_mod".to_owned(),
            },
        ];
        let src = generate_harness_source(&root, &discovered);
        assert!(src.contains("mod _scenario_forward_turn_stop"));
        assert!(src.contains("mod _scenario_from_mod"));
        assert!(src.contains("scenarios/forward_turn_stop.rs"));
        assert!(src.contains("scenarios/from_mod/mod.rs"));
        assert!(src.contains("fn main() -> phoxal::Result<()>"));
    }
}
