[package]
name = "phoxal-runtime-safety"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
phoxal = { workspace = true, features = ["scenario"] }
async-trait = { workspace = true }
nalgebra = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
