[package]
name = "phoxal-service-odometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official service: odometry - differential-drive wheel-odometry estimator."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-odometry"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true, features = ["participant"] }
anyhow = { workspace = true }

[lints]
workspace = true
