//! The single API layer: the versioned contract tree every participant speaks.
//!
//! It depends only on the
//! [`phoxal-bus`](phoxal_bus) ABI floor (the contract primitive traits and the
//! typed-topic builders) and the [`phoxal-macros`](phoxal_macros) proc-macros; it
//! does **not** depend on the `phoxal` engine. Normal participants import the
//! train-selected facade with `use phoxal::api`; concrete modules such as
//! `phoxal_api::v0_1` are available to compatibility adapters.
//!
//! # Concrete API revisions
//!
//! An API revision is a conventional `vM_N` module generated by
//! [`phoxal_api_tree!`]. Each version module carries:
//!
//! - a zero-variant marker `enum Api {}` implementing [`ApiVersion`], whose
//!   [`ApiVersion::ID`] is the concrete wire identity (for example `"v0.1"`);
//! - the version-local wire bodies, one `pub mod` per contract node holding plain
//!   serde structs/enums and their [`ContractBody`] impls. A body is bound to
//!   exactly one [`ApiVersion`] and one contract topic; handles, `SetupContext`
//!   builders, and the `Service`/`Driver` derive assertions all key off its
//!   `Api`/`TOPIC`;
//! - an api-local `topic` builder rooted at `topic::client()`.
//!
//! From 1.0, published concrete revisions are immutable. Before 1.0 the
//! framework may make an approved in-place breaking edit without adding a shim
//! or a new revision; every participant on a robot must move as one train
//! because mixed pre-1.0 framework trains are unsupported. A child may extend
//! one earlier revision; the generator materializes the complete child tree
//! with its own identity. Exactly one `latest` alias is selected for each
//! framework train.
//!
//! # Train-selected revision and per-contract identity
//!
//! A participant creates typed bus handles during
//! `phoxal::Participant::setup`. Official participants
//! name contract types through the complete train-selected facade. Embedded
//! participant metadata carries `{id, config_schema}`.
//! Across the graph, compatibility is **name identity** - two participants
//! interoperate on a contract iff they use the exact same version-qualified name
//! (`v0.1::drive::Target`), which is real on the wire because the revision
//! is folded into the key ([`ContractBody::TOPIC`]). From 1.0 onward a stable
//! contract type is immutable, so the name is the whole identity. Before 1.0,
//! that identity is train-scoped and an in-place edit requires the whole robot
//! graph to upgrade together.
//!
//! # Plain serde wire bodies, provenance in metadata
//!
//! A wire body is just its serde encoding - there is no `{"v":…}` envelope or any
//! other version tag inside the payload. Identity lives entirely in the
//! Zenoh key (the version-qualified [`ContractBody::TOPIC`]); the bus metadata
//! alongside the encoded body carries only provenance (source + logical time) and
//! the codec that produced the bytes - never schema/family/version. Keeping
//! identity out of both the payload and the metadata means the body bytes for an
//! unchanged contract are identical across codecs, and a receiver's per-key
//! subscription is the whole fast-reject.
//!
//! # Topic
//!
//! [`ContractBody::TOPIC`] is derived from the contract node's path in the tree,
//! never written by hand: the version, then the `/`-joined node path plus the
//! topic leaf, with each dynamic node contributing a `{var}` placeholder, e.g.
//! `v0.1/component/{instance}/motor/{capability}/command`. A fully static path
//! has a literal key (`v0.1/drive/state`). Folding the revision into the key is
//! what makes two differently-versioned contracts physically distinct Zenoh
//! keys, so they cannot collide.
//!
//! # The api-local topic builder
//!
//! Each version module exposes a `topic` builder that mirrors the node tree:
//! `api::topic::client()` returns a root, one method per top-level node walks down the
//! tree, a dynamic node's method takes its variable as `impl Display`, and a leaf
//! method binds the topic's side-branded kind to its version-local body. For
//! example `api::topic::client().drive().state()` yields a
//! `Topic<Subscribe<drive::State>>` (the CLIENT observes the owner's `state`) over
//! the version-qualified key `v0.1/drive/state`, and
//! `api::topic::client().component("base").motor("left").command()` fills the dynamic
//! segments to produce `v0.1/component/base/motor/left/command`. Because the
//! builder is generated from the same tree as `TOPIC`, the built key and the
//! documented key stay in lockstep.
//!
//! ## Owner side: `topic::owner`
//!
//! The PUBLIC `topic::client()...` chain above is the **client** side. The matching
//! **owner** side lives at `api::topic::owner()...`:
//! the same node tree and keys, but the leaf brands flip so the owner gets the side
//! it must take - `api::topic::owner().drive().state()` is
//! `Topic<Publish<drive::State>>` (the owner publishes its telemetry), and
//! `api::topic::owner().drive().target()` is `Topic<Subscribe<drive::Target>>`
//! (the owner reads its command input). A query owner reaches its `ServeQuery`
//! brand the same way. The owner chain makes that ownership explicit; a
//! participant acquires the topics of its OWN node through it and everything it
//! consumes through the client chain.
//!
//! [`ApiVersion`]: phoxal_bus::ApiVersion
//! [`ApiVersion::ID`]: phoxal_bus::ApiVersion::ID
//! [`ContractBody`]: phoxal_bus::ContractBody
//! [`ContractBody::TOPIC`]: phoxal_bus::ContractBody::TOPIC

mod api;
pub use api::*;
pub use phoxal_macros::{phoxal_api, phoxal_api_tree};

mod domains;

/// The exact camera capability reference accepted by `video/open`.
///
/// This is API-owned because the contract crate intentionally does not depend
/// upward on the runtime model. It has the same canonical dotted spelling as
/// the model reference (`component.capability`), but deserialization rejects
/// malformed or aliased source names before a query reaches a service.
#[derive(
    serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[serde(try_from = "String", into = "String")]
pub struct VideoSourceRef(String);

/// A validated dotted capability source reference.
///
/// This is the generic form of [`VideoSourceRef`]. The older name remains a
/// type alias so the published v0.1 video request keeps the same Rust and wire
/// surface while newer contracts can reuse the exact same validation without
/// depending on the runtime model crate.
pub type SourceRef = VideoSourceRef;

impl VideoSourceRef {
    /// Construct an already validated wire reference.
    pub fn parse(value: impl Into<String>) -> Result<Self, InvalidVideoSourceRef> {
        value.into().try_into()
    }

    /// The canonical dotted source spelling.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Why a `VideoSourceRef` failed its exact wire grammar.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvalidVideoSourceRef(String);

/// Generic spelling of the validation error for [`SourceRef`].
pub type InvalidSourceRef = InvalidVideoSourceRef;

impl std::fmt::Display for InvalidVideoSourceRef {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "invalid video source reference '{}'; expected component.capability",
            self.0
        )
    }
}

impl std::error::Error for InvalidVideoSourceRef {}

impl TryFrom<String> for VideoSourceRef {
    type Error = InvalidVideoSourceRef;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let Some((component, capability)) = value.split_once('.') else {
            return Err(InvalidVideoSourceRef(value));
        };
        if value.matches('.').count() != 1
            || !valid_video_source_segment(component)
            || !valid_video_source_segment(capability)
        {
            return Err(InvalidVideoSourceRef(value));
        }
        Ok(Self(value))
    }
}

impl From<VideoSourceRef> for String {
    fn from(value: VideoSourceRef) -> Self {
        value.0
    }
}

fn valid_video_source_segment(value: &str) -> bool {
    !value.is_empty()
        && value.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_' || byte == b'-'
        })
}

/// Deserialize a control-target scalar without allowing a non-finite value to
/// enter a lease or a wheel-mixing calculation. The target fields remain plain
/// `f32`s on the wire; their explicitly restricted visibility and this serde
/// hook make serde enforce the same invariant as `Target::try_new`.
pub(crate) fn deserialize_finite_target_scalar<'de, D>(deserializer: D) -> Result<f32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f32 as serde::Deserialize>::deserialize(deserializer)?;
    value
        .is_finite()
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("control target scalar must be finite"))
}

/// Reject non-finite v0.2 motor command scalars during wire deserialization.
pub(crate) fn deserialize_finite_motor_scalar<'de, D>(deserializer: D) -> Result<f32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f32 as serde::Deserialize>::deserialize(deserializer)?;
    value
        .is_finite()
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("motor command scalar must be finite"))
}

/// Reject a non-finite confidence score on the current perception wire.
pub(crate) fn deserialize_finite_detection_confidence<'de, D>(
    deserializer: D,
) -> Result<f32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f32 as serde::Deserialize>::deserialize(deserializer)?;
    value
        .is_finite()
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("perception confidence must be finite"))
}

/// Reject a non-finite coordinate in the current perception wire position.
///
/// Deserializing into `[f64; 3]` also enforces the fixed three-coordinate
/// shape, so malformed vectors cannot enter the detector/tracker boundary.
pub(crate) fn deserialize_finite_detection_position<'de, D>(
    deserializer: D,
) -> Result<[f64; 3], D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <[f64; 3] as serde::Deserialize>::deserialize(deserializer)?;
    value
        .iter()
        .all(|coordinate| coordinate.is_finite())
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("perception position must be finite"))
}

/// Deserialize a map scalar that participates in a world-space bound.
pub(crate) fn deserialize_finite_map_scalar<'de, D>(deserializer: D) -> Result<f64, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f64 as serde::Deserialize>::deserialize(deserializer)?;
    value
        .is_finite()
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("map coordinate must be finite"))
}

/// A map window dimension is part of a checked `width * height` shape, so zero
/// is not a valid wire value even before the cell vector is considered.
pub(crate) fn deserialize_nonzero_map_dimension<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <u32 as serde::Deserialize>::deserialize(deserializer)?;
    (value != 0)
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("map window dimensions must be nonzero"))
}

/// Grid resolution is a physical scalar rather than an arbitrary float.
pub(crate) fn deserialize_finite_positive_resolution<'de, D>(
    deserializer: D,
) -> Result<f32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f32 as serde::Deserialize>::deserialize(deserializer)?;
    (value.is_finite() && value > 0.0)
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("map resolution must be finite and positive"))
}

/// A frame name is part of the map identity and may not be absent or blank.
pub(crate) fn deserialize_nonempty_frame_id<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <String as serde::Deserialize>::deserialize(deserializer)?;
    (!value.trim().is_empty())
        .then_some(value)
        .ok_or_else(|| serde::de::Error::custom("map frame id must not be empty"))
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GridBoundsWire {
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub min_x_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub min_y_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub max_x_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub max_y_m: f64,
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GridPoseWire {
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub x_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub y_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub yaw_rad: f64,
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GridPointWire {
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub x_m: f64,
    #[serde(deserialize_with = "crate::deserialize_finite_map_scalar")]
    pub y_m: f64,
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GridWindowWire {
    #[serde(deserialize_with = "crate::deserialize_nonempty_frame_id")]
    pub frame_id: String,
    pub origin_pose: crate::domains::v0_2::map::Pose,
    pub cell_origin: crate::domains::v0_2::map::Point,
    #[serde(deserialize_with = "crate::deserialize_finite_positive_resolution")]
    pub resolution_m: f32,
    #[serde(deserialize_with = "crate::deserialize_nonzero_map_dimension")]
    pub width: u32,
    #[serde(deserialize_with = "crate::deserialize_nonzero_map_dimension")]
    pub height: u32,
    pub cells: Vec<crate::domains::v0_2::map::Occupancy>,
    pub revision: u64,
    pub requested: crate::domains::v0_2::map::Bounds,
    pub covered: crate::domains::v0_2::map::Bounds,
}

#[doc(hidden)]
#[derive(Debug, Clone)]
pub struct GridWireError(pub &'static str);

impl std::fmt::Display for GridWireError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.0)
    }
}

impl std::error::Error for GridWireError {}

fn deserialize_finite_nonnegative_safety_limit<'de, D>(deserializer: D) -> Result<f32, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <f32 as serde::Deserialize>::deserialize(deserializer)?;
    (value.is_finite() && value >= 0.0)
        .then_some(value)
        .ok_or_else(|| {
            serde::de::Error::custom("safety speed limit must be finite and nonnegative")
        })
}

fn deserialize_optional_finite_safety_value<'de, D>(
    deserializer: D,
) -> Result<Option<f32>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <Option<f32> as serde::Deserialize>::deserialize(deserializer)?;
    value
        .map(|value| {
            value
                .is_finite()
                .then_some(value)
                .ok_or_else(|| serde::de::Error::custom("safety observed value must be finite"))
        })
        .transpose()
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub enum SafetyMotionPermissionWire {
    Clear,
    Limited {
        #[serde(deserialize_with = "crate::deserialize_finite_nonnegative_safety_limit")]
        effective_linear_speed_mps: f32,
        #[serde(deserialize_with = "crate::deserialize_finite_nonnegative_safety_limit")]
        effective_angular_speed_radps: f32,
        reasons: Vec<crate::domains::v0_2::safety::ConstraintReason>,
    },
    Stopped {
        reasons: Vec<crate::domains::v0_2::safety::ConstraintReason>,
    },
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub enum SafetyConstraintWire {
    Limited {
        reason: crate::domains::v0_2::safety::ConstraintReason,
        source: crate::domains::v0_2::safety::ConstraintSource,
        #[serde(deserialize_with = "crate::deserialize_finite_nonnegative_safety_limit")]
        max_linear_speed_mps: f32,
        #[serde(deserialize_with = "crate::deserialize_finite_nonnegative_safety_limit")]
        max_angular_speed_radps: f32,
        #[serde(deserialize_with = "crate::deserialize_optional_finite_safety_value")]
        observed_value: Option<f32>,
        valid_from: ::phoxal_bus::RobotInstant,
        expires_at: ::phoxal_bus::RobotInstant,
    },
    Stopped {
        reason: crate::domains::v0_2::safety::ConstraintReason,
        source: crate::domains::v0_2::safety::ConstraintSource,
        #[serde(deserialize_with = "crate::deserialize_optional_finite_safety_value")]
        observed_value: Option<f32>,
        valid_from: ::phoxal_bus::RobotInstant,
        expires_at: ::phoxal_bus::RobotInstant,
    },
}

#[doc(hidden)]
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SafetyMotionConstraintsWire {
    pub sequence: u64,
    pub permission: SafetyMotionPermissionWire,
    pub constraints: Vec<SafetyConstraintWire>,
    pub expires_at: ::phoxal_bus::RobotInstant,
}

impl TryFrom<GridBoundsWire> for crate::domains::v0_2::map::Bounds {
    type Error = GridWireError;

    fn try_from(value: GridBoundsWire) -> Result<Self, Self::Error> {
        if !(value.min_x_m < value.max_x_m && value.min_y_m < value.max_y_m) {
            return Err(GridWireError("map bounds must have positive extent"));
        }
        Ok(Self {
            min_x_m: value.min_x_m,
            min_y_m: value.min_y_m,
            max_x_m: value.max_x_m,
            max_y_m: value.max_y_m,
        })
    }
}

impl TryFrom<GridPoseWire> for crate::domains::v0_2::map::Pose {
    type Error = GridWireError;

    fn try_from(value: GridPoseWire) -> Result<Self, Self::Error> {
        Ok(Self {
            x_m: value.x_m,
            y_m: value.y_m,
            yaw_rad: value.yaw_rad,
        })
    }
}

impl TryFrom<GridPointWire> for crate::domains::v0_2::map::Point {
    type Error = GridWireError;

    fn try_from(value: GridPointWire) -> Result<Self, Self::Error> {
        Ok(Self {
            x_m: value.x_m,
            y_m: value.y_m,
        })
    }
}

impl TryFrom<GridWindowWire> for crate::domains::v0_2::map::GridWindow {
    type Error = GridWireError;

    fn try_from(value: GridWindowWire) -> Result<Self, Self::Error> {
        let expected = usize::try_from(value.width)
            .ok()
            .and_then(|width| {
                usize::try_from(value.height)
                    .ok()
                    .and_then(|height| width.checked_mul(height))
            })
            .ok_or(GridWireError("map grid dimensions overflow"))?;
        if value.cells.len() != expected {
            return Err(GridWireError(
                "map grid cell shape does not match dimensions",
            ));
        }
        if !(value.covered.min_x_m >= value.requested.min_x_m
            && value.covered.min_y_m >= value.requested.min_y_m
            && value.covered.max_x_m <= value.requested.max_x_m
            && value.covered.max_y_m <= value.requested.max_y_m)
        {
            return Err(GridWireError(
                "map covered bounds must be contained in requested bounds",
            ));
        }
        let epsilon = f64::from(value.resolution_m) * 1.0e-6;
        if (value.cell_origin.x_m - value.covered.min_x_m).abs() > epsilon
            || (value.cell_origin.y_m - value.covered.min_y_m).abs() > epsilon
        {
            return Err(GridWireError(
                "map cell origin must equal the covered lower corner",
            ));
        }
        if (value.origin_pose.x_m - value.cell_origin.x_m).abs() > epsilon
            || (value.origin_pose.y_m - value.cell_origin.y_m).abs() > epsilon
        {
            return Err(GridWireError(
                "map origin pose translation must equal the cell origin",
            ));
        }
        let covered_width = f64::from(value.width) * f64::from(value.resolution_m);
        let covered_height = f64::from(value.height) * f64::from(value.resolution_m);
        if (value.covered.max_x_m - value.covered.min_x_m - covered_width).abs() > epsilon
            || (value.covered.max_y_m - value.covered.min_y_m - covered_height).abs() > epsilon
        {
            return Err(GridWireError("map covered bounds do not match grid extent"));
        }
        Ok(Self {
            frame_id: value.frame_id,
            origin_pose: value.origin_pose,
            cell_origin: value.cell_origin,
            resolution_m: value.resolution_m,
            width: value.width,
            height: value.height,
            cells: value.cells,
            revision: value.revision,
            requested: value.requested,
            covered: value.covered,
        })
    }
}

impl TryFrom<SafetyMotionPermissionWire> for crate::domains::v0_2::safety::MotionPermission {
    type Error = GridWireError;

    fn try_from(value: SafetyMotionPermissionWire) -> Result<Self, Self::Error> {
        match value {
            SafetyMotionPermissionWire::Clear => Ok(Self::Clear),
            SafetyMotionPermissionWire::Limited {
                effective_linear_speed_mps,
                effective_angular_speed_radps,
                reasons,
            } if !reasons.is_empty() => Ok(Self::Limited {
                effective_linear_speed_mps,
                effective_angular_speed_radps,
                reasons,
            }),
            SafetyMotionPermissionWire::Stopped { reasons } if !reasons.is_empty() => {
                Ok(Self::Stopped { reasons })
            }
            _ => Err(GridWireError(
                "safety permission must carry reasons for limited or stopped motion",
            )),
        }
    }
}

impl TryFrom<SafetyConstraintWire> for crate::domains::v0_2::safety::Constraint {
    type Error = GridWireError;

    fn try_from(value: SafetyConstraintWire) -> Result<Self, Self::Error> {
        let (source, valid_from, expires_at) = match &value {
            SafetyConstraintWire::Limited {
                source,
                valid_from,
                expires_at,
                ..
            }
            | SafetyConstraintWire::Stopped {
                source,
                valid_from,
                expires_at,
                ..
            } => (source, *valid_from, *expires_at),
        };
        let validity = valid_from.checked_cmp(expires_at);
        if source.participant_id.trim().is_empty()
            || !validity.is_ok_and(|order| order != std::cmp::Ordering::Greater)
        {
            return Err(GridWireError(
                "safety constraint source and validity interval are invalid",
            ));
        }
        Ok(match value {
            SafetyConstraintWire::Limited {
                reason,
                source,
                max_linear_speed_mps,
                max_angular_speed_radps,
                observed_value,
                valid_from,
                expires_at,
            } => Self::Limited {
                reason,
                source,
                max_linear_speed_mps,
                max_angular_speed_radps,
                observed_value,
                valid_from,
                expires_at,
            },
            SafetyConstraintWire::Stopped {
                reason,
                source,
                observed_value,
                valid_from,
                expires_at,
            } => Self::Stopped {
                reason,
                source,
                observed_value,
                valid_from,
                expires_at,
            },
        })
    }
}

impl TryFrom<SafetyMotionConstraintsWire> for crate::domains::v0_2::safety::MotionConstraints {
    type Error = GridWireError;

    fn try_from(value: SafetyMotionConstraintsWire) -> Result<Self, Self::Error> {
        let permission = value.permission.try_into()?;
        let constraints = value
            .constraints
            .into_iter()
            .map(TryInto::try_into)
            .collect::<Result<Vec<crate::domains::v0_2::safety::Constraint>, GridWireError>>()?;
        let expected = expected_safety_permission(&constraints)?;
        if permission != expected {
            return Err(GridWireError(
                "safety permission disagrees with its constraints",
            ));
        }
        for constraint in &constraints {
            let (valid_from, expires_at) = match constraint {
                crate::domains::v0_2::safety::Constraint::Limited {
                    valid_from,
                    expires_at,
                    ..
                }
                | crate::domains::v0_2::safety::Constraint::Stopped {
                    valid_from,
                    expires_at,
                    ..
                } => (*valid_from, *expires_at),
            };
            if value.expires_at.checked_cmp(expires_at).is_err()
                || !value
                    .expires_at
                    .checked_cmp(expires_at)
                    .is_ok_and(|order| order != std::cmp::Ordering::Less)
            {
                return Err(GridWireError(
                    "safety product expiry must cover every constraint",
                ));
            }
            if valid_from.checked_cmp(value.expires_at).is_err() {
                return Err(GridWireError("safety product uses mixed timelines"));
            }
        }
        Ok(Self {
            sequence: value.sequence,
            permission,
            constraints,
            expires_at: value.expires_at,
        })
    }
}

fn expected_safety_permission(
    constraints: &[crate::domains::v0_2::safety::Constraint],
) -> Result<crate::domains::v0_2::safety::MotionPermission, GridWireError> {
    let reasons = constraints
        .iter()
        .map(|constraint| match constraint {
            crate::domains::v0_2::safety::Constraint::Limited { reason, .. }
            | crate::domains::v0_2::safety::Constraint::Stopped { reason, .. } => reason.clone(),
        })
        .collect::<Vec<_>>();
    if constraints
        .iter()
        .any(|constraint| matches!(constraint, crate::domains::v0_2::safety::Constraint::Stopped { .. }))
    {
        return Ok(crate::domains::v0_2::safety::MotionPermission::Stopped { reasons });
    }
    if constraints.is_empty() {
        return Ok(crate::domains::v0_2::safety::MotionPermission::Clear);
    }
    let mut linear = f32::MAX;
    let mut angular = f32::MAX;
    for constraint in constraints {
        let crate::domains::v0_2::safety::Constraint::Limited {
            max_linear_speed_mps,
            max_angular_speed_radps,
            ..
        } = constraint
        else {
            return Err(GridWireError("safety constraint shape is contradictory"));
        };
        linear = linear.min(*max_linear_speed_mps);
        angular = angular.min(*max_angular_speed_radps);
    }
    Ok(crate::domains::v0_2::safety::MotionPermission::Limited {
        effective_linear_speed_mps: linear,
        effective_angular_speed_radps: angular,
        reasons,
    })
}

#[cfg(test)]
mod tests;
