[package]
name = "phoxal-service-asset"
version = "0.19.5"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = true
description = "Phoxal official service: asset - serves robot-root assets over the bus."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-asset"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }

[lints]
workspace = true
