[package]
name = "phoxal-service-asset"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official service: asset - serves bundle-root assets over the bus."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-asset"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }

[lints]
workspace = true
