[package]
name = "phoxal-component-ddsm115"
version = "0.0.0-dev.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: ddsm115 - wheel hub motor."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["api/**", "build.rs", "src/**", "Cargo.toml", "Cargo.lock", "LICENSE", "README.md", "component.yaml", "model.xml", "assets/**"]

[[bin]]
name = "phoxal-component-ddsm115"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = ["runtime"]
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["contract", "robotics"] }
anyhow = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[build-dependencies]
phoxal = { workspace = true, default-features = false, features = ["build"] }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
