[package]
name = "phoxal-component-ddsm115"
version = "0.68.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal"]
description = "Phoxal official driver: ddsm115 - wheel hub motor."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["build.rs", "src/**", "proto/**", "Cargo.toml", "component.yaml", "model.xml", "assets/**"]

[package.metadata.phoxal]
kind = "component"

[lib]
name = "phoxal_component_ddsm115"
path = "src/lib.rs"

[[bin]]
name = "phoxal-component-ddsm115"
path = "src/main.rs"
required-features = ["runtime"]

[features]
default = ["runtime"]
runtime = ["phoxal/runtime", "dep:anyhow", "dep:serde", "dep:phoxal-service-motion"]

[dependencies]
phoxal = { workspace = true, default-features = false, features = ["port"] }
anyhow = { workspace = true, optional = true }
phoxal-service-motion = { workspace = true, optional = true }
phoxal-robotics = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, optional = true }

[build-dependencies]
phoxal = { workspace = true, default-features = false, features = ["build"] }
phoxal-robotics = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
