[package]
name = "phoxal-service-drive"
version = "0.19.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official service: drive - differential-drive body-twist control."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-service-drive"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
