[package]
name = "phoxal-tool-router"
version = "0.1.11"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Phoxal official tool: router - site-local Zenoh router artifact."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "phoxal-tool-router"
path = "src/main.rs"

[dependencies]
phoxal = { workspace = true }
phoxal-api = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zenoh = { workspace = true }

[lints]
workspace = true
